### ISSUE TITLE
TypeError: Value of "this" must be of type URLSearchParams

### ISSUE THREAD

**Issue by kuntal-c** [zabirauf/AutoGPT.js#23]
TypeError: Value of "this" must be of type URLSearchParams
    at new NodeError (node:internal/errors:399:5)
    at Proxy.set (node:internal/url:519:13)
    at Proxy.<anonymous> (/Users/kc/AutoGPT.js/node_modules/@remix-run/web-fetch/src/headers.js:124:44)
    at createRemixHeaders (/Users/kc/AutoGPT.js/node_modules/@remix-run/express/dist/server.js:57:17)
    at createRemixRequest (/Users/kc/AutoGPT.js/node_modules/@remix-run/express/dist/server.js:71:14)
    at /Users/kc/AutoGPT.js/node_modules/@remix-run/express/dist/server.js:37:21
    at /Users/kc/AutoGPT.js/node_modules/@remix-run/serve/dist/index.js:47:7
    at Layer.handle [as handle_request] (/Users/kc/AutoGPT.js/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kc/AutoGPT.js/node_modules/express/lib/router/route.js:144:13)
    at next (/Users/kc/AutoGPT.js/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/kc/AutoGPT.js/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/kc/AutoGPT.js/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/kc/AutoGPT.js/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/kc/AutoGPT.js/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/kc/AutoGPT.js/node_modules/express/lib/router/route.js:140:7)
    at Route.dispatch (/Users/kc/AutoGPT.js/node_modules/express/lib/router/route.js:114:3)

**Comment by zabirauf** [comment]
@ICreativeKid can you share how are you running it and OS, Browser versions.

**Comment by zabirauf** [comment]
#33  should fix it
