### ISSUE TITLE
TypeError: Value of "this" must be of type URLSearchParams

### ISSUE THREAD

**Issue by ivan-vilches** [zabirauf/AutoGPT.js#28]
Hello folks i run the commands :
1- Copy .env.example to .env and change as necessary. 
in this point i keep:
DATABASE_URL="file:./data.db?connection_limit=1"  (its needed install sqlite? or crete the data.db ?
SESSION_SECRET="super-duper-s3cret"   (i didnt touch that)
Run npm install to get all the dependencies.
Run npm run dev to start the development server.

my os:
macos monterrey 12.4 
mac air m1 2020 
browser chrome 112.0.5615.49
Thanks you !!!!!

i got this:
TypeError: Value of "this" must be of type URLSearchParams
    at new NodeError (node:internal/errors:399:5)
    at Proxy.set (node:internal/url:519:13)
    at Proxy.<anonymous> (/Users/myuser/Documents/proyectos/Estudios/autogptjs/node_modules/@remix-run/web-fetch/src/headers.js:124:44)
    at createRemixHeaders (/Users/myuser/Documents/proyectos/Estudios/autogptjs/node_modules/@remix-run/express/dist/server.js:57:17)
    at createRemixRequest (/Users/myuser/Documents/proyectos/Estudios/autogptjs/node_modules/@remix-run/express/dist/server.js:71:14)
    at /Users/myuser/Documents/proyectos/Estudios/autogptjs/node_modules/@remix-run/express/dist/server.js:37:21
    at /Users/myuser/Documents/proyectos/Estudios/autogptjs/node_modules/@remix-run/serve/dist/index.js:47:7
    at Layer.handle [as handle_request] (/Users/myuser/Documents/proyectos/Estudios/autogptjs/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/myuser/Documents/proyectos/Estudios/autogptjs/node_modules/express/lib/router/route.js:144:13)
    at next (/Users/myuser/Documents/proyectos/Estudios/autogptjs/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/myuser/Documents/proyectos/Estudios/autogptjs/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/myuser/Documents/proyectos/Estudios/autogptjs/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/myuser/Documents/proyectos/Estudios/autogptjs/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/myuser/Documents/proyectos/Estudios/autogptjs/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/myuser/Documents/proyectos/Estudios/autogptjs/node_modules/express/lib/router/route.js:140:7)
    at Route.dispatch (/Users/myuser/Documents/proyectos/Estudios/autogptjs/node_modules/express/lib/router/route.js:114:3)

**Comment by zabirauf** [comment]
#33 should fix it
